// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenEcologyApp.Data;

#nullable disable

namespace OpenEcologyApp.Migrations
{
    [DbContext(typeof(EcologyDbContext))]
    partial class EcologyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("OpenEcologyApp.Data.GrainHarvest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GrossHarvest")
                        .HasColumnType("REAL");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SownArea")
                        .HasColumnType("REAL");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Yield")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("GrainHarvests");
                });
#pragma warning restore 612, 618
        }
    }
}
